// Auto-generated by supabase. Do not change this file.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type ImpactLevel = "LOW" | "MEDIUM" | "HIGH"

export interface Moment {
  created_at: string
  description: string | null
  id: string
  impact: ImpactLevel
  source: string | null
  tags: string[] | null
  time_of_day: string | null
  title: string
  type: string
  user_id: string
}

export interface MomentInsert {
  created_at?: string
  description?: string | null
  id?: string
  impact?: ImpactLevel
  source?: string | null
  tags?: string[] | null
  time_of_day?: string | null
  title: string
  type: string
  user_id?: string
}

export interface MomentUpdate {
  created_at?: string
  description?: string | null
  id?: string
  impact?: ImpactLevel
  source?: string | null
  tags?: string[] | null
  time_of_day?: string | null
  title?: string
  type?: string
  user_id?: string
}

export type Database = {
  public: {
    Tables: {
      moments: {
        Row: Moment
        Insert: MomentInsert
        Update: MomentUpdate
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      impact_level: ImpactLevel
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

export type MomentRow = Database['public']['Tables']['moments']['Row']
export type MomentInsertRow = Database['public']['Tables']['moments']['Insert']
export type MomentUpdateRow = Database['public']['Tables']['moments']['Update']

export const IMPACT_LEVELS = ["LOW", "MEDIUM", "HIGH"] as const
